export const lightTheme = {
  welcomeBackground: '#00000080',
  bodyBackground: '#E2E2E2',
  panelBackground: '#FFF',
  buttonBackground: '#FFF',
  buttonBackgroundHover: '#0059a3',
  buttonTextColor: '#0059a3',
  buttonTextColorHover: '#FFF',
  materialButtonColor: '#3c62b5',
  staticTextColor: '#000',
  secondaryTextColor: 'grey',
  inactiveUser: '#9c9c9c',
  inputLabel: 'rgba(0, 0, 0, 0.54)',
  inputLabelFocused: '#303f9f',
};

export const darkTheme = {
  welcomeBackground: '#000000CB',
  bodyBackground: '#282828',
  panelBackground: '#1f1f1f',
  buttonBackground: '#232323',
  buttonBackgroundHover: '#3e3e3e',
  buttonTextColor: '#FAFAFA',
  buttonTextColorHover: '#bdf3ff',
  materialButtonColor: '#0086e6',
  staticTextColor: '#FFF',
  secondaryTextColor: 'grey',
  inactiveUser: '#9c9c9c',
  inputLabel: '#acacac',
  inputLabelFocused: '#0086e6',
};
